package com.maudio.online.player;

import android.app.PendingIntent;
import android.content.Intent;
import android.os.Build;

import androidx.annotation.Nullable;
import androidx.annotation.OptIn;
import androidx.media3.common.AudioAttributes;
import androidx.media3.common.C;
import androidx.media3.common.MediaItem;
import androidx.media3.common.util.UnstableApi;
import androidx.media3.datasource.DefaultDataSource;
import androidx.media3.datasource.DefaultHttpDataSource;
import androidx.media3.exoplayer.DefaultLoadControl;
import androidx.media3.exoplayer.ExoPlayer;
import androidx.media3.exoplayer.source.DefaultMediaSourceFactory;
import androidx.media3.session.MediaLibraryService;
import androidx.media3.session.MediaSession;

import com.maudio.online.MainActivity;

/**
 * Native MAUDIO playback service.
 *
 * Owns the one and only ExoPlayer instance for the app. Because playback lives in
 * a foreground MediaLibraryService (not the WebView), Android 13/14/15 keeps audio
 * alive with the screen locked, the notification is generated by Media3 itself
 * (correct MediaStyle + artwork + compact actions), and Bluetooth head units plus
 * Android Auto can browse and control the library.
 */
@OptIn(markerClass = UnstableApi.class)
public class MaudioPlayerService extends MediaLibraryService {

    private static final String USER_AGENT = "MAUDIO/1.0 (Android)";

    private ExoPlayer player;
    private MediaLibrarySession session;

    @Override
    public void onCreate() {
        super.onCreate();

        DefaultHttpDataSource.Factory httpFactory = new DefaultHttpDataSource.Factory()
                .setUserAgent(USER_AGENT)
                .setConnectTimeoutMs(20_000)
                .setReadTimeoutMs(30_000)
                .setAllowCrossProtocolRedirects(true);

        // DefaultDataSource wraps the HTTP factory and also resolves file:// and
        // content:// URIs, so downloaded/cached tracks play through the same path.
        DefaultDataSource.Factory dataSourceFactory =
                new DefaultDataSource.Factory(this, httpFactory);

        DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
                .setBufferDurationsMs(15_000, 60_000, 1_500, 3_000)
                .build();

        AudioAttributes audioAttributes = new AudioAttributes.Builder()
                .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
                .setUsage(C.USAGE_MEDIA)
                .build();

        player = new ExoPlayer.Builder(this)
                .setMediaSourceFactory(new DefaultMediaSourceFactory(dataSourceFactory))
                .setLoadControl(loadControl)
                // Media3 requests/abandons audio focus for us: ducks on notifications,
                // pauses on calls, resumes afterwards.
                .setAudioAttributes(audioAttributes, true)
                .setHandleAudioBecomingNoisy(true)
                .setWakeMode(C.WAKE_MODE_NETWORK)
                .setSeekBackIncrementMs(10_000)
                .setSeekForwardIncrementMs(30_000)
                .build();
        player.setPauseAtEndOfMediaItems(false);

        session = new MediaLibrarySession.Builder(this, player, new MaudioLibraryCallback(this))
                .setSessionActivity(buildSessionActivity())
                .setId("maudio_playback")
                .build();
    }

    private PendingIntent buildSessionActivity() {
        Intent intent = new Intent(this, MainActivity.class)
                .setAction(Intent.ACTION_MAIN)
                .addCategory(Intent.CATEGORY_LAUNCHER)
                .setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
        int flags = PendingIntent.FLAG_UPDATE_CURRENT
                | (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M ? PendingIntent.FLAG_IMMUTABLE : 0);
        return PendingIntent.getActivity(this, 0, intent, flags);
    }

    @Nullable
    @Override
    public MediaLibrarySession onGetSession(MediaSession.ControllerInfo controllerInfo) {
        return session;
    }

    @Override
    public void onTaskRemoved(@Nullable Intent rootIntent) {
        // Swiping the app away should not kill music that is still playing, but it
        // should tear the service down cleanly once playback has stopped.
        if (player == null || !player.getPlayWhenReady() || player.getMediaItemCount() == 0) {
            stopSelf();
        }
    }

    @Override
    public void onDestroy() {
        if (session != null) {
            session.release();
            session = null;
        }
        if (player != null) {
            player.release();
            player = null;
        }
        super.onDestroy();
    }
}
